management:
  endpoints:
    web:
      exposure:
        include: ['env', 'refresh'] # 엔드 포인트 ex) http://localhost:9265/actuator/refresh (POST)
        
spring:
  config:
    import: 
      optional:
        configserver: http://localhost:8888